name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animated_list:
    git: https://github.com/vaetas/animated_list.git
  animations: ^2.0.7
  drift: ^2.6.0
  drift_dev: ^2.6.0
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.0
  flutter_hooks: ^0.18.6
  flutter_native_splash: ^2.2.19
  freezed_annotation: ^2.2.0
  device_preview: ^1.1.0
  go_router: ^6.4.0
  heroicons: ^0.8.0
  hooks_riverpod: ^2.3.2
  intl: ^0.18.0
  json_annotation: ^4.8.0
  local_auth: ^2.1.6
  path: ^1.8.3
  path_provider: ^2.0.14
  pressable: ^0.5.0
  sqlite3_flutter_libs: ^0.5.13
  url_launcher: ^6.1.10
  awesome_snackbar_content: 0.1.3
  badges: ^3.1.2
  cupertino_icons: ^1.0.2
  draggable_fab: ^0.1.4
  flashy_tab_bar2: ^0.0.4
  google_fonts: ^6.1.0
  lottie: ^1.4.3
  syncfusion_flutter_calendar: ^20.3.52

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon_launcher.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon_launcher.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon_launcher.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/font/Poppins-Regular.ttf
          weight: 500
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Bold.ttf
          weight: 800
        - asset: assets/font/Poppins-ExtraBold.ttf
          weight: 900
