// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALge6ajwHPy20FhHmFtv318ywreynoNGs',
    appId: '1:36693461614:web:3a2c9cec3fd44b29f1747f',
    messagingSenderId: '36693461614',
    projectId: 'pijak-91dc9',
    authDomain: 'pijak-91dc9.firebaseapp.com',
    storageBucket: 'pijak-91dc9.appspot.com',
    measurementId: 'G-2P4M4295PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHq000Qt8l3YvhVTRADGUy8NIMz-RM2mE',
    appId: '1:36693461614:android:916b2b211922a932f1747f',
    messagingSenderId: '36693461614',
    projectId: 'pijak-91dc9',
    storageBucket: 'pijak-91dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSM4cvCbaqJPjYd557CYw9vdQwM6247WU',
    appId: '1:36693461614:ios:007ffacc1d01a38ff1747f',
    messagingSenderId: '36693461614',
    projectId: 'pijak-91dc9',
    storageBucket: 'pijak-91dc9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSM4cvCbaqJPjYd557CYw9vdQwM6247WU',
    appId: '1:36693461614:ios:b86bf954f344d9b1f1747f',
    messagingSenderId: '36693461614',
    projectId: 'pijak-91dc9',
    storageBucket: 'pijak-91dc9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
